version: '3.1'

services:
  server:
    container_name: server
    build:
      context: ./server/
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      DBUSER: root
      DBPASS: example
      DBADRESS: workshop_db:3306
      DBNAME: workshop_docker
    ports:
      - 8080:8080

  db:
    container_name: workshop_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql-data:/var/lib/mysql
      - ./server/mysql/:/docker-entrypoint-initdb.d
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080
    depends_on:
      - "db"

volumes:
  mysql-data: